### ISSUE TITLE
Cannot create convos/add people to existing konvo

### ISSUE THREAD

**Issue by Burpie** [bjorngrunde/FL#25]
Om jag skapar en en konvo med folk blir jag ensam i den.

Tar jag lägg till fler personer får jag "En användare kunde inte hittas. Försök igen" error

**Comment by bjorngrunde** [comment]
Jodå! Du skrivver personens namn, sen trycker du TAB, sen skriver du en ny persons namn och Trycker TAB så läggs de till i en lista :D
