### ISSUE TITLE
Creating raid

### ISSUE THREAD

**Issue by Burpie** [bjorngrunde/FL#32]
Use default values raid-start 19:30 and raid end 23:00.

Description field should not be mandatory.

**Comment by bjorngrunde** [comment]
Blir löjligt mycket jobb för något så enkelt som att bara välja en tid. Och tanken med raids senare är ju att kunna skapa andra event med, Challenge Modes osv :P Och hur gör man om det är en alt raid på en lördag med andra tider?

**Comment by Burpie** [comment]
Hur kan det vara mycket jobb att ha ett för-ifyllt värde i en text-box? Alltså Date elementet ska vara kvar, bara att värdet innan man ändrar det istället för vara tomt ska vara föreslagna tiderna.

**Comment by bjorngrunde** [comment]
Aha då hänger jag med. Ska ordna det.

**Comment by Burpie** [comment]
Haha inte så lätt! Insåg inte det kunde innebära ta bort date elementet :D

**Comment by bjorngrunde** [comment]
aja, nu är det fixat. Tog 23 sekunder. :D

**Comment by Burpie** [comment]
Lol!
